kafka:
  url: "localhost:29092"
  group_id: "ledger_service_group"
  consumer_topics:
    - create_ledger
    - create_transaction

db:
  host: localhost
  port: 5432
  user: ledger
  password: pg_ledger
  database: ledger
